# .github/workflows/publish-to-ghcr.yml

name: Build and Push to GHCR

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to write packages
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK for building the Java application
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # 3. Build the application with Maven to create the JAR file
      #    Replace with './gradlew bootJar' if you use Gradle
      - name: Build with Gradle
        run: ./gradlew bootJar

      # 4. Log in to the GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Extract metadata (tags, labels) for the Docker image
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # 6. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}